apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed to the outside world
      targetPort: 8000  # Internal FastAPI port
  type: LoadBalancer